title: My WildCat Studios Portfolio 
description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://ar362058.github.io" # replace AR362958 with your GitHub username
theme: jekyll-theme-hacker # replace with your chosen theme from the list
